DROP DATABASE IF EXISTS ELOAN;

CREATE DATABASE ELOAN;

USE ELOAN;

CREATE TABLE USERS(
USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(50),
DOB DATE,
GENDER VARCHAR(10),
EMAIL_ID VARCHAR(50),
PWD VARCHAR(30),
CREATED_DT DATE
);

CREATE TABLE eloan_roles(
 	user_name varchar(20) primary key,
 	password varchar(20) not null,
 	role varchar(10) not null
 ); 

CREATE TABLE LOAN_REQ(
LOAN_APPL_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USER_NAME VARCHAR(50),
LOAN_NAME VARCHAR(100),
LOAN_AMOUNT DECIMAL(10,2),
LOAN_APPL_DATE DATE,
LOAN_BUS_STRC VARCHAR(30),
LOAN_BILL_IND VARCHAR(30),
MOBILE INT,
ADDRESS VARCHAR(200),
PURPOSE VARCHAR(200),
LOAN_TERM_MNTHS INT,
STATUS VARCHAR(20));
ALTER TABLE LOAN_REQ AUTO_INCREMENT = 101;

CREATE TABLE USER_LOAN_INFO(
LOAN_NUM INT NOT NULL PRIMARY KEY AUTO_INCREMENT, FOREIGN KEY (Loan_APPL_ID) REFERENCES LOAN_REQ(Loan_APPL_ID),
LOAN_APPL_ID INT,
SANCTIONED_AMT DECIMAL(10,2),
LOAN_TERM_MNTHS INT,
PAYMENT_START_DT DATE,
LOAN_CLOSURE_DT DATE,
LOAN_EMI_AMT DECIMAL(10,2),
TOTAL_PAYMENT_AMT DECIMAL(10,2),
LOAN_INTEREST_RATE DECIMAL(10,2));
ALTER TABLE USER_LOAN_INFO AUTO_INCREMENT = 1111;